FROM centos:8

Label "maintainer"="alp514@lehigh.edu" \
      "os"="CentOS 8" \
      "compiler"="GCC 8.3.0" \
      "app"="R 4.0.3" \
      "app"="RStudio 1.3.1056" \
      "description"="R 4.0.3 and RStudio 1.3.1056" 

COPY install_rver.sh /opt
COPY install_rpack.R /opt
 
# Install epel-release
RUN yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm \
 && sed -i.bak -e 's/enabled=0/enable=1/g' /etc/yum.repos.d/CentOS-Linux-PowerTools.repo \
 && yum -y install glibc-langpack-en epel-release wget git \
 && yum -y update

# Install R 4.0.3 and add to PATH
RUN sh /opt/install_rver.sh 4.0.3 
ENV PATH /opt/R/4.0.3/bin:$PATH

# Set default repo
RUN (echo '' \
 &&  echo 'local({' \
 &&  echo '    r <- getOption("repos")' \
 &&  echo '    r["CRAN"] <- "http://lib.stat.cmu.edu/R/CRAN"' \
 &&  echo '    options(repos=r)' \
 &&  echo '})' \
 &&  echo '' ) >>  /opt/R/4.0.3/lib/R/library/base/R/Rprofile

# Install dependencies for some basic R packages
RUN yum -y autoremove \
 && yum -y install wget openssl-devel cyrus-sasl-devel libxml2-devel file-devel \
 && rm -rf /var/cache/yum \
 && yum clean all

# Install some basic R packages
RUN Rscript -e "install.packages('BiocManager')" 
RUN Rscript -e "BiocManager::install(c('rvest','dplyr','devtools'))"

# Install RStudio 1.3.1056
RUN cd /opt/ \
 && wget https://download2.rstudio.org/server/centos8/x86_64/rstudio-server-rhel-1.3.1056-x86_64.rpm \
 && yum -y install rstudio-server-rhel-1.3.1056-x86_64.rpm \
 && rm -rf rstudio-server-rhel-1.3.1056-x86_64.rpm \
 && rm -rf /var/cache/yum \
 && yum clean all

# Run R when executing container, default option is --version
ENTRYPOINT ["/usr/local/bin/R"]
CMD ["--version"]


