FROM alexpacheco/rstudio:r-403-base

Label "maintainer"="alp514@lehigh.edu" \
      "os"="CentOS 8" \
      "compiler"="GCC 8.3.0" \
      "app"="R 4.0.3" \
      "app"="RStudio 1.2.1335" \
      "description"="R 4.0.3 and RStudio 1.2.1335" 

# Install dependencies for geospatial packages
RUN yum -y install hdf5-devel netcdf-devel \
 && wget http://repo.okay.com.mx/centos/8/x86_64/release/v8-6.7.17-8.el8.x86_64.rpm \
 && wget http://repo.okay.com.mx/centos/8/x86_64/release/v8-devel-6.7.17-8.el8.x86_64.rpm \
 && wget https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/j/jq-1.6-2.el7.x86_64.rpm \
 && https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/j/jq-devel-1.6-2.el7.x86_64.rpm \
 && yum -y install v8-6.7.17-8.el8.x86_64.rpm v8-devel-6.7.17-8.el8.x86_64.rpm jq-1.6-2.el7.x86_64.rpm jq-devel-1.6-2.el7.x86_64.rpm \
 && rm -rf /var/cache/yum *.rpm \
 && yum clean all
 
# Install R geo packages
RUN Rscript -e "source('/opt/install_rpack.R'); BiocManager::install(install_package(geo)); nrow(as.data.frame(installed.packages())) "
# Install R spactial view packages
RUN Rscript -e "source('/opt/install_rpack.R'); BiocManager::install(install_package(spatial)); nrow(as.data.frame(installed.packages())) "
# Install alberusa package
RUN Rscript -e "remotes::install_git('https://git.rud.is/hrbrmstr/albersusa.git')"

