FROM alexpacheco/rstudio:r-403-base

Label "maintainer"="alp514@lehigh.edu" \
      "os"="CentOS 8" \
      "compiler"="GCC 8.3.0" \
      "app"="R 4.0.3" \
      "app"="RStudio 1.2.1335" \
      "description"="R 4.0.3 and RStudio 1.2.1335" 

# Install R bio packages

RUN Rscript /opt/install_rpack.R lubio

