FROM alexpacheco/rstudio:r-363

Label "maintainer"="alp514@lehigh.edu" \
      "os"="CentOS 8" \
      "compiler"="GCC 8.3.0" \
      "app"="R 3.6.3" \
      "app"="RStudio 1.3.1056" \
      "description"="R 3.6.3 and RStudio 1.2.1335" 

COPY install_3x.R /opt

RUN Rscript /opt/install_3x.R


