install.packages(c('BiocManager','devtools'))

if ( as.integer(R.Version()$major) < 4 ) { # R < 4.x
  devtools::install_version('XML', version = '3.99-0.3')
  devtools::install_version('foreign', version = '0.8-76')
  devtools::install_version('mnormt', version = '1.5-7')
  devtools::install_version('nloptr', version = '1.2.2')
  # R 3.5.3
  if ( as.double(R.Version()$minor) < 6 ) { # R < 3.6.x
    devtools::install_version('caTools', version = '1.17.1.4')
    devtools::install_version('glmnet', version = '2.0-18')
    devtools::install_version('text2vec', version = '0.5-1')
    devtools::install_version('amap', version = '0.8-16')
    devtools::install_version('latticeExtra', version = '0.6-28')
    devtools::install_version('ROCR', version = '1.0-7')
    tidy <- c()
  } else { # R > 3.6.x && R < 4.x
    tidy <- c('car','caTools','glmnet','metap','text2vec')
  }
} 

tidy <- c( tidy, 
              'broom', 
              'caret', 
              'choroplethr',
              'curl',
	      'dataCompareR',
              'DataExplorer',
              'datapasta',
              'data.table', 
              'dplyr', 
              'DT',
	      'dygraphs',
	      'echarts4r',
              'esquisse',
	      'feather',
	      'flexdashboard',
              'forcats', 
              'formatR',
	      'fst',
              'future',
              'gganimate',
	      'ggforce',
	      'ggmap',
              'ggplot2', 
              'ggvis',
	      'githubinstall',
	      'gmodels',
	      'googleAnalyticsR',
	      'googleAuthR',
              'googlesheets4',
	      'googleVis',
	      'highcharter',
              'htmlTable', 
              'janitor', 
              'kableExtra', 
              'knitr', 
              'leaflet',
	      'listviewer',
              'lubridate',
	      'openxlsx',
              'maps',
              'mlr', 
              'odbc',
	      'officer',
	      'pacman',
	      'patchwork',
              'plotly',
	      'plumber',
	      'profvis',
              'quantmod', 
              'rbokeh', 
              'Rcrawler',
	      'remedy',
              'remotes', 
              'rmarkdown', 
              'RSQLite', 
              'rvest',
	      'scales',
              'selectr',
	      'shiny',
              'snow', 
              'SnowballC',
              'splitstackshape', 
              'stringi', 
              'testthat',
              'tidyquant',
              'tidyr',
              'tidytext', 
              'tidyverse',
              'tidyxl',
              'tsbox',
              'usmap',
              'validate',
              'xts')

lubio <- c( 'ape',
               'argparse',
               'bigmemory',
               'Biobase',
               'biomaRt',
               'Biostrings',
               'caret',
               'circlize',
               'crosstalk',
               'ctc',
               'dendextend',
               'DESeq2',
               'DEXSeq',
               'doParallel',
               'DT',
               'edgeR',
               'fastcluster',
               'flashClust',
               'formatR',
               'geneLenDataBase',
               'GenomicAlignments',
               'GenomicFeatures',
               'Glimma',
               'GOplot',
               'goseq',
               'gplots',
               'Heatplus',
               'Hmisc',
               'htmlTable',
               'igraph',
               'kableExtra',
               'lme4',
               'micropan',
               'microseq',
               'MLSeq',
               'multtest',
               'parallelDist',
               'phangorn',
               'phytools',
               'pvclust',
               'qvalue',
               'randomForest',
               'Rdpack',
               'remotes',
               'RMySQL',
               'ROTS',
               'RPostgreSQL',
               'Rsamtools',
               'RSQLite',
               'rtracklayer',
               'Rtsne',
               'sctransform',
               'selectr',
               'seqinr',
               'Seurat',
               'sm',
               'sqldf',
               'stringi',
               'tibble',
               'tidyverse',
               'tximport',
               'tximportData',
               'uwot',
               'vegan',
               'VennDiagram',
               'WGCNA',
               'zoo')

geo <- c( 'classInt',
              'deldir',
              'geofacet',
              'geoR',
              'geosphere',
              'gstat',
              'hdf5r',
              'lidR',
              'mapdata',
              'mapsapi',
              'maptools',
              'mapview',
              'ncdf4',
              'proj4',
              'RandomFields',
              'raster',
              'RColorBrewer',
              'rgdal',
              'rgeos',
              'rlas',
              'RNetCDF',
              'sf',
              'sp',
              'spacetime',
              'spatstat',
              'spdep',
              'sf', 
	      'tidycensus',
	      'tmap',
	      'tmaptools')

BiocManager::install(c(tidy,lubio))

warnings()

